packages:
  - "apps/frontend"
  - "apps/backend"
allowBuilds:
  '@nestjs/core': true
  bcrypt: true
  better-sqlite3: true
  esbuild: true
  unrs-resolver: false
onlyBuiltDependencies:
  - "@nestjs/core"
  - better-sqlite3
  - bcrypt
  - esbuild
